### ISSUE TITLE
Ho do I stop it treating the question numbers as marks?

### ISSUE THREAD

**Issue by paulleader** [andrerpbts/ruby_marks#8]
Hi there,

First up, thanks so much for this library, it's brilliant.

I'm having a bit of a problem with it interpreting the question numbers on a mark sheet as marks. You can see what I mean in this image https://res.cloudinary.com/logicprep/image/upload/v1449072062/irwqram7q0rnbqzsbtfk.png

I've tried all sorts of options, I'm specifying the area as tightly as possible, but it keeps including the numbers and then mistakenly counting some of them as filled in marks.

Do you have any suggestions on how to stop this happening?

Thanks, Paul

**Comment by andrerpbts** [comment]
Hi, 

Try to adjust the [Intensity Percentual](https://github.com/andrerpbts/ruby_marks#intensity-percentual) to a value above 50, something near 70 I bet. It will make less sensible to number of black pixels, and will require better filled marks. 

But, you can add the [Scan Unmarked Watcher](https://github.com/andrerpbts/ruby_marks#scan-unmarked-watcher), to do some code if some line not find any marks, like mark this test for a human analysis, for example.

It's important to remember, probably you'll not have 100% accuracy in all test forms, one or another will have something that the reader can't recognize well. So, watchers are completely useful in this way.

Still note, that grid scan mode for your form is a good way to handle your form, see? This have bubbles in a such tabled organization, so you can apply the grid in the group. I'm sorry because grid scan mode isn't very well documented, maybe you will need to look the code (I know, someday I'll refactor this :grimacing:).

Thank you for using it, and any question, don't hesitate to ask here :)

**Comment by paulleader** [comment]
Thanks for that, very much appreciated.

Do I need to configure the grid scan differently?

I tried just switching to grid scan but it seems to be completely off, here's the same sheet - https://res.cloudinary.com/logicprep/image/upload/v1449144619/vi8gbqprqtr5zblp15le.png

Do I need to configure grid scan differently to the default scan mode?

**Comment by andrerpbts** [comment]
Hmm, 

If I understood well, it seems to be right, no? The marks was recognized. The only difference of default scan and grid mode, is: default scan will perform flood scan to recognize lines and will detect between spaces and lines, each mark. In the other hand, we have grid, which will "draw" a table, based in mark height and width, and will suppose the center of each mark.

The result isn't ok?

**Comment by andrerpbts** [comment]
@paulleader Can you post you code here, please? Let me take a look...
